### PR TITLE
fixes link to maven

### PR DESCRIPTION
**Pull request by tieskedh**
link without protocol was internal link

### CODE REVIEW

**Comment by edvin** [comment]
The existing link also encodes the search text:

g:"no.tornado" AND a:"tornadofx"

This is missing from your replacement. Where did this link not work? It seems to be working fine for me, and it has a protocol (http).

**Comment by tieskedh** [comment]
search.maven.org has no https/https.

Browser: Chrome, 
Page: https://edvin.gitbooks.io/tornadofx-guide/content/2.%20Setting%20Up.html
Header: Manual Import
Link: Central Repository
problem: links to https://edvin.gitbooks.io/tornadofx-guide/content/search.maven.org instead of https://search.maven.org
fix: add procol to link

**Comment by edvin** [comment]
Ah, sorry - I looked at the link above that :)

**Comment by tieskedh** [comment]
All right. Up to the next contribution ;-)

**Pull request merged**
