### PR TITLE
Fix declaration of age variable in person

### PR DESCRIPTION
**Pull request by IEnoobong**
Age was previously `Int` but it can't be binded to `column`, changed to SimpleIntegerProperty to allow for binding

I need help with the new screenshot please

### CODE REVIEW

**Comment by edvin** [comment]
You can still bind a non observable value, so this doesn't need to change. You could however make an integerBinding based on the birthday property, so that changes to the birthday would auotmatically reflect in the tableview. However, birthdays don't change so often, so I'd say it's just wrong to create a property for this readonly field :)

**Comment by IEnoobong** [comment]
@edvin but trying to as int gives this error
Screenshot from 2019-03-18 08-54-11

**Comment by edvin** [comment]
You must use `readonlyColumn()`

**Comment by IEnoobong** [comment]
I see, then I'll change the PR to use `readonlyColumn` there then

**Comment by edvin** [comment]
Perfect, thanks :) This syntax used to be valid, but we had to rename the column builders for non observables due to type shadowing issues.

**Pull request merged**
